<a href="https://colab.research.google.com/github/25wh1a05bz-beep/NASSCOM/blob/main/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------


In [2]:
import numpy as np

print("\n--- Task 1: Array Creation Shortcuts ---")

arr1_1 = np.arange(0, 100)


arr1_2 = np.ones((3, 3))


arr1_3 = np.full((2, 4), 7)


arr1_4 = np.random.randint(10, 51, (5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[22 40 23 17 32]
 [28 26 20 34 29]]


In [3]:
print("\n--- Task 2: Indexing and Slicing with Arrays ---")

data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])

val2_1 = data[2, 3]

row2_2 = data[0]

col2_3 = data[:, 3]

sub_arr2_4 = data[1:3, 0:2]

filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)


--- Task 2: Indexing and Slicing with Arrays ---
val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [4]:
print("\n--- Task 3: Conditional Operations ---")

arr3_1 = np.random.randint(1, 21, size=(4, 5))  # Random 4x5 array with values 1 to 20

# 3.1 Replace elements less than 10 with 0
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2 Count the number of even elements
even_count3_3 = np.sum(arr3_1 % 2 == 0)

# Print the results
print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("Number of even elements:", even_count3_3)


--- Task 3: Conditional Operations ---
arr3_1:
 [[ 2  1 17 16 13]
 [ 6  2  2 19  3]
 [ 8 15 20  1  3]
 [17 20 14  6 10]]
arr3_2:
 [[ 0  0 17 16 13]
 [ 0  0  0 19  0]
 [ 0 15 20  0  0]
 [17 20 14  0 10]]
Number of even elements: 11


In [5]:
print("\n--- Task 4: Aggregation Functions ---")

arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])


sum4_1 = np.sum(arr4_1)


mean_cols4_2 = np.mean(arr4_1, axis=0)

max_rows4_3 = np.max(arr4_1, axis=1)

std4_4 = np.std(arr4_1)

print("Sum of all elements:", sum4_1)
print("Mean of each column:", mean_cols4_2)
print("Maximum value in each row:", max_rows4_3)
print("Standard deviation:", std4_4)


--- Task 4: Aggregation Functions ---
Sum of all elements: 84
Mean of each column: [11.          6.66666667 10.33333333]
Maximum value in each row: [12 15 20]
Standard deviation: 5.2493385826745405


In [6]:
print("\n--- Task 5: Reshaping and Flattening ---")

arr5_1 = np.arange(24)

reshaped_arr5_2 = arr5_1.reshape(4, 6)

reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)

flattened_arr5_4 = reshaped_arr5_2.ravel()      # View
flattened_arr5_4_flat = reshaped_arr5_2.flatten()  # Copy

print("Original array:\n", arr5_1)

print("\nReshaped to 4x6:\n", reshaped_arr5_2)

print("\nReshaped to 2x3x4:\n", reshaped_arr5_3)

print("\nFlattened using ravel():\n", flattened_arr5_4)

print("\nFlattened using flatten():\n", flattened_arr5_4_flat)


--- Task 5: Reshaping and Flattening ---
Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Reshaped to 4x6:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

Reshaped to 2x3x4:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

Flattened using ravel():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

Flattened using flatten():
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [7]:
print("\n--- Task 6: Broadcasting ---")

arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

scalar = 10
vector = np.array([100, 200, 300])

# 6.1 Add the scalar to every element
result6_1 = arr6_1 + scalar

# 6.2 Add the vector to each row
result6_2 = arr6_1 + vector

# Print the results
print("Original Array:\n", arr6_1)
print("\nAfter adding scalar:\n", result6_1)
print("\nAfter adding vector:\n", result6_2)


--- Task 6: Broadcasting ---
Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

After adding scalar:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

After adding vector:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [8]:
print("\n--- Task 7: Copying vs. Viewing Arrays ---")

original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1 Create a view by slicing the entire array
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("After modifying view_arr7:")
print("original_arr7:", original_arr7)
print("view_arr7    :", view_arr7)

# 7.2 Create a copy using .copy()
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("\nAfter modifying copy_arr7:")
print("original_arr7:", original_arr7)
print("copy_arr7    :", copy_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
After modifying view_arr7:
original_arr7: [99  2  3  4  5]
view_arr7    : [99  2  3  4  5]

After modifying copy_arr7:
original_arr7: [99  2  3  4  5]
copy_arr7    : [99  2  3  4  0]


In [9]:
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2], [3, 4]])
arr8_b = np.array([[5, 6], [7, 8]])
arr8_c = np.array([[9, 10]])

vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

part1, part2, part3, part4, part5 = np.vsplit(combined_arr8_3, 5)

print("Vertical Stack:\n", vstack_arr8_1)

print("\nHorizontal Stack:\n", hstack_arr8_2)

print("\nCombined Array:\n", combined_arr8_3)

print("\nPart 1:\n", part1)
print("Part 2:\n", part2)
print("Part 3:\n", part3)
print("Part 4:\n", part4)
print("Part 5:\n", part5)


--- Task 8: Stacking and Splitting Arrays ---
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]

Combined Array:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Part 1:
 [[1 2]]
Part 2:
 [[3 4]]
Part 3:
 [[5 6]]
Part 4:
 [[7 8]]
Part 5:
 [[ 9 10]]


In [10]:
print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])
arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

sorted_arr9_1 = np.sort(arr9_1)

sorted_cols9_2 = np.sort(arr9_2d, axis=0)

idx9_3 = np.where(arr9_1 == 9)

max_idx9_4 = np.argmax(arr9_1)

print("Sorted arr9_1:", sorted_arr9_1)
print("\nSorted columns:\n", sorted_cols9_2)
print("\nIndex of value 9:", idx9_3)
print("Index of maximum value:", max_idx9_4)


--- Task 9: Sorting and Searching ---
Sorted arr9_1: [1 2 3 4 5 6 7 8 9]

Sorted columns:
 [[30 20 10]
 [60 50 40]
 [90 80 70]]

Index of value 9: (array([4]),)
Index of maximum value: 4
