<a href="https://colab.research.google.com/github/25wh1a05bz-beep/NASSCOM/blob/main/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

s1_1 = pd.Series([10, 20, 30, 40, 50])

np_array1_2 = np.random.randint(1, 101, (3, 4))

df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("Series s1_1:")
print(s1_1)

print("\nNumPy Array:")
print(np_array1_2)

print("\nDataFrame df1_3:")
print(df1_3)



--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[ 85  61   1  20]
 [ 98  11  31  11]
 [ 34 100  94  67]]

DataFrame df1_3:
    A    B   C   D
0  85   61   1  20
1  98   11  31  11
2  34  100  94  67


In [2]:
import numpy as np
import pandas as pd

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

df_sales = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', end='2023-04-10')[:100],
    'Region': np.random.choice(['East', 'West', 'North', 'South'], 100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], 100),
    'Sales': np.random.randint(100, 1001, 100).astype(float),
    'Quantity': np.random.randint(1, 11, 100).astype(float)
})

sales_nan_idx = np.random.choice(df_sales.index, 5, replace=False)
df_sales.loc[sales_nan_idx, 'Sales'] = np.nan

quantity_nan_idx = np.random.choice(df_sales.index, 3, replace=False)
df_sales.loc[quantity_nan_idx, 'Quantity'] = np.nan

print(df_sales.head(10))



--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  305.0       9.0
1 2023-01-02  South     Mouse  994.0       7.0
2 2023-01-03   West     Mouse  488.0       7.0
3 2023-01-04  South   Monitor  956.0       9.0
4 2023-01-05   East    Laptop  337.0       3.0
5 2023-01-06   East   Monitor  110.0       5.0
6 2023-01-07   East     Mouse  879.0       2.0
7 2023-01-08  North     Mouse  735.0       2.0
8 2023-01-09   East  Keyboard  505.0       5.0
9 2023-01-10  North  Keyboard  687.0       7.0


In [3]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

df3_1 = df_sales[['Region', 'Sales']]

df3_2 = df_sales[df_sales['Product'] == 'Laptop']

df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]

val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]

print("Region and Sales columns:")
print(df3_1.head())

print("\nRows where Product is Laptop:")
print(df3_2.head())

print("\nRows where Region is East and Sales > 500:")
print(df3_3.head())

print("\nSales value for first Monitor entry:", val3_4)


--- Task 3: Indexing and Slicing in DataFrames ---
Region and Sales columns:
  Region  Sales
0   West  305.0
1  South  994.0
2   West  488.0
3  South  956.0
4   East  337.0

Rows where Product is Laptop:
         Date Region Product   Sales  Quantity
4  2023-01-05   East  Laptop   337.0       3.0
16 2023-01-17  South  Laptop   923.0      10.0
19 2023-01-20  North  Laptop   317.0       2.0
22 2023-01-23  North  Laptop   354.0       3.0
26 2023-01-27  South  Laptop  1000.0      10.0

Rows where Region is East and Sales > 500:
         Date Region   Product  Sales  Quantity
6  2023-01-07   East     Mouse  879.0       2.0
8  2023-01-09   East  Keyboard  505.0       5.0
30 2023-01-31   East     Mouse  598.0       2.0
34 2023-02-04   East    Laptop  829.0       9.0
42 2023-02-12   East     Mouse  827.0       6.0

Sales value for first Monitor entry: 956.0


In [4]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

missing_counts4_1 = df_sales.isnull().sum()

df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(df4_2_filled['Sales'].mean())

df4_3_dropped = df_sales.dropna()

print("Missing values in each column:")
print(missing_counts4_1)

print("\nDataFrame after filling missing Sales values:")
print(df4_2_filled.head())

print("\nDataFrame after dropping rows with missing values:")
print(df4_3_dropped.head())


--- Task 4: Data Cleaning (Handling Missing Values) ---
Missing values in each column:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

DataFrame after filling missing Sales values:
        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  305.0       9.0
1 2023-01-02  South     Mouse  994.0       7.0
2 2023-01-03   West     Mouse  488.0       7.0
3 2023-01-04  South   Monitor  956.0       9.0
4 2023-01-05   East    Laptop  337.0       3.0

DataFrame after dropping rows with missing values:
        Date Region   Product  Sales  Quantity
0 2023-01-01   West  Keyboard  305.0       9.0
1 2023-01-02  South     Mouse  994.0       7.0
2 2023-01-03   West     Mouse  488.0       7.0
3 2023-01-04  South   Monitor  956.0       9.0
4 2023-01-05   East    Laptop  337.0       3.0


In [5]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'],
                                    ascending=[True, False])

df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("DataFrame with Total_Revenue:")
print(df_sales.head())

print("\nSorted DataFrame:")
print(df5_2_sorted.head())

print("\nTotal Sales and Quantity by Region:")
print(df5_3_grouped_region)

print("\nAverage Sales by Product:")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---
DataFrame with Total_Revenue:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   West  Keyboard  305.0       9.0         2745.0
1 2023-01-02  South     Mouse  994.0       7.0         6958.0
2 2023-01-03   West     Mouse  488.0       7.0         3416.0
3 2023-01-04  South   Monitor  956.0       9.0         8604.0
4 2023-01-05   East    Laptop  337.0       3.0         1011.0

Sorted DataFrame:
        Date Region   Product  Sales  Quantity  Total_Revenue
0 2023-01-01   West  Keyboard  305.0       9.0         2745.0
1 2023-01-02  South     Mouse  994.0       7.0         6958.0
2 2023-01-03   West     Mouse  488.0       7.0         3416.0
3 2023-01-04  South   Monitor  956.0       9.0         8604.0
4 2023-01-05   East    Laptop  337.0       3.0         1011.0

Total Sales and Quantity by Region:
          Sales  Quantity
Region                   
East    13294.0     139.0
North   12587.0     116.0
So